### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by MichaelJCompton** [MichaelJCompton/GraphSchemaTools#1]
In progress

- [ ] Further GraphQL spec compliance (https://github.com/MichaelJCompton/GraphSchemaTools/issues/2)
- [ ] Fully checking schemas on input (https://github.com/MichaelJCompton/GraphSchemaTools/issues/5)
- [ ] Update mutations

soon

- [ ] hosting GraphSchema instances 
- [ ] delete semantics (delete mutations + cascading deletes)

longer term

- [ ] more to come
